name: "App Add Request"
description: "Add a new web app to the registry"
title: "Add app: "

body:
  - type: markdown
    attributes:
      value: "Fill out the form below and `apps.json` will be updated automatically."
  - type: input
    id: title
    attributes:
      label: "App name"
      description: "Example: Awesome App"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: "URL"
      description: "Example: https://example.com"
    validations:
      required: true
